### ISSUE TITLE
how to add additional packages to an install of homeport

### ISSUE THREAD

**Issue by vielmetti** [bigeasy/homeport#16]
I built homeport and got it to launch, yay. Now I'm looking at how to get some more packages installed, especially a few that I end up compiling or loading every time I get to a new system. What did you have in mind to handle that?

**Comment by bigeasy** [comment]
Currently, if you:

```
$ homeport create --user ed --hub vielmetti
$ homeport append zsh rsync
$ homeport append git build-essential
```

Each one will add a new layer, two Dockerfile commands, that will install from `apt-get`.

```
$ homeport clear
```

Will take you back to the foundation.

**Comment by vielmetti** [comment]
```
Edwards-MacBook-Air:homeport emv$ HOMEPORT_PATH=$(pwd) ./homeport create --user emv --account vielmetti
getopt: unrecognized option '--account'
/Users/emv/src/homeport/lib/create: line 17: return: can only `return' from a function or sourced script
```

**Comment by bigeasy** [comment]
`--account` should be `--hub`. I updated the comment above.

**Comment by bigeasy** [comment]
I updated it just now, so it was wrong when you tried. You shouldn't have to type `HOMEPORT_PATH=` it should figure that out itself. If it can't, let me know.

**Comment by vielmetti** [comment]
Yeah, when I don't type ``HOMEPORT_PATH=` I get this

```
Edwards-MacBook-Air:homeport emv$ set | grep HOMEPORT
Edwards-MacBook-Air:homeport emv$ ./homeport help
./homeport: line 111: /getopt.bash: No such file or directory
```

```
Edwards-MacBook-Air:homeport emv$ ./homeport append jq
./homeport: line 111: /getopt.bash: No such file or directory
```

I

**Comment by vielmetti** [comment]
When I launch the shell it drops me in as root:

```
Edwards-MacBook-Air:homeport emv$ docker run -it vielmetti/homeport_shell
root@41a1cc7194c8:/# 
root@41a1cc7194c8:/# whoami
root
```

**Comment by bigeasy** [comment]
Let me finish the launch program.

**Comment by bigeasy** [comment]
```
$ homeport create --user emv --hub vielmette
$ homeport append formula/jq
$ homeport append git vim zsh rsync
$ homeport append formula/node
$ homeport append psmisc
$ homeport home
$ homeport run
```

The above packages are not required, they are just examples.

**Comment by bigeasy** [comment]
We can keep talking here, but I'm going to close it because It Works on My Machine™.
