### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by jgpelletier** [bigeasy/homeport#24]
when I run either 
`./homeport create --user joshua --hub jgpelletier`
or 
`./homeport create --user joshua --account jgpelletier` 
I get `./homeport: line 111: /getopt.bash: No such file or directory`

**Comment by bigeasy** [comment]
The `HOMEPORT_PATH` is correctly resolved when `homeport` is a symlink, but not when you run `./homeport` directly.

**Comment by bigeasy** [comment]
I've closed this because It Works on My Machine™. Let me know if you're still having difficulty.

**Comment by jgpelletier** [comment]
Is this what is needed to create the symlink `ln -s
/Users/joshua/git/pub/homeport
homeport?

**Comment by bigeasy** [comment]
You would symlink it somewhere in your path.

I create a directory so I can symlink from Homebrew.

```
$ mkdir -p /usr/local/Cellar/homeport/0.0.0/bin
$ cd /usr/local/Cellar/homeport/0.0.0/bin
$ ln -s /Users/alan/projects/homeport/homeport
$ brew link homeport
```

Now I can run `homeport` from anywhere.
