### ISSUE TITLE
Install `homeport` through `brew tap`

### ISSUE THREAD

**Issue by vielmetti** [bigeasy/homeport#46]
So one way to get applications onto a Mac through `brew` is to set up a `tap` with your own repo with its own install instructions. That might be useful for `homeport`.

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/brew-tap.md

is the docs.

**Comment by bigeasy** [comment]
http://formalfriday.club/2015/01/05/creating-your-own-homebrew-tap-and-formula.html

**Comment by bigeasy** [comment]
Note to self: `install.bin` and `install.share` will install Homeport.

**Comment by bigeasy** [comment]
Good call Ed. Great way to get people on board faster.

**Comment by bigeasy** [comment]
Good call @vielmetti. Great way to get people on board faster.
